# Generated by Django 4.2.5 on 2024-03-08 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('betweenStreet', models.CharField(max_length=100)),
                ('colony', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=5, null=True)),
                ('number', models.CharField(max_length=5, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AppoinmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('pyment_ype', models.CharField(max_length=100)),
                ('appoinment_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorManager.appoinmentservice')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('ocupation', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=150, null=True)),
                ('reason_consult', models.CharField(max_length=200, null=True)),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorManager.address')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('professionalID', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('university', models.CharField(max_length=150)),
                ('speciality', models.CharField(max_length=150, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorManager.address')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=30)),
                ('scheduled', models.DateTimeField(auto_now_add=True)),
                ('coment', models.CharField(max_length=500, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorManager.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorManager.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appoinmentservice',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorManager.appointment'),
        ),
        migrations.AddField(
            model_name='appoinmentservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorManager.service'),
        ),
    ]
